spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miero?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Hong9201$
  profiles: local
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ycdlmysql.cnifrwbhjfrb.ap-northeast-2.rds.amazonaws.com/miero?useUnicode=true&characterEncoding=utf-8
    username: hong2
    password: Hong9201$
